# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.28)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS PDFHummus::Zlib PDFHummus::FreeType PDFHummus::LibAesgm PDFHummus::LibJpeg PDFHummus::LibTiff PDFHummus::LibPng PDFHummus::PDFWriter)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target PDFHummus::Zlib
add_library(PDFHummus::Zlib STATIC IMPORTED)

set_target_properties(PDFHummus::Zlib PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_UNISTD_H=1"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/lorwy/Code/github_projects/other/PDF-Writer/Zlib"
)

# Create imported target PDFHummus::FreeType
add_library(PDFHummus::FreeType STATIC IMPORTED)

set_target_properties(PDFHummus::FreeType PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "FT2_BUILD_LIBRARY=1;FT_CONFIG_OPTION_SYSTEM_ZLIB=1"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/lorwy/Code/github_projects/other/PDF-Writer/FreeType/include"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib"
)

# Create imported target PDFHummus::LibAesgm
add_library(PDFHummus::LibAesgm STATIC IMPORTED)

set_target_properties(PDFHummus::LibAesgm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibAesgm"
)

# Create imported target PDFHummus::LibJpeg
add_library(PDFHummus::LibJpeg STATIC IMPORTED)

set_target_properties(PDFHummus::LibJpeg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibJpeg"
)

# Create imported target PDFHummus::LibTiff
add_library(PDFHummus::LibTiff STATIC IMPORTED)

set_target_properties(PDFHummus::LibTiff PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "HAVE_UNISTD_H=1;_CRT_SECURE_NO_DEPRECATE=1;AVOID_WIN32_FILEIO=1;CHECK_JPEG_YCBCR_SUBSAMPLING=1;DEFAULT_EXTRASAMPLE_AS_ALPHA=1;STRIPCHOP_DEFAULT=TIFF_STRIPCHOP;STRIP_SIZE_DEFAULT=8192;PIXARLOG_SUPPORT=1;ZIP_SUPPORT=1;LOGLUV_SUPPORT=1;NEXT_SUPPORT=1;THUNDER_SUPPORT=1;LZW_SUPPORT=1;PACKBITS_SUPPORT=1;CCITT_SUPPORT=1;TIF_PLATFORM_CONSOLE=1;FILLODER_LSB2MSB=1"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibTiff"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib"
)

# Create imported target PDFHummus::LibPng
add_library(PDFHummus::LibPng STATIC IMPORTED)

set_target_properties(PDFHummus::LibPng PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibPng"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib"
)

# Create imported target PDFHummus::PDFWriter
add_library(PDFHummus::PDFWriter STATIC IMPORTED)

set_target_properties(PDFHummus::PDFWriter PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/lorwy/Code/github_projects/other/PDF-Writer/PDFWriter"
  INTERFACE_LINK_LIBRARIES "PDFHummus::Zlib;PDFHummus::FreeType;PDFHummus::LibAesgm;PDFHummus::LibJpeg;PDFHummus::LibTiff;PDFHummus::LibPng"
)

# Import target "PDFHummus::Zlib" for configuration "Debug"
set_property(TARGET PDFHummus::Zlib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(PDFHummus::Zlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/lorwy/Code/github_projects/other/PDF-Writer/Zlib/Debug/libZlib.a"
  )

# Import target "PDFHummus::FreeType" for configuration "Debug"
set_property(TARGET PDFHummus::FreeType APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(PDFHummus::FreeType PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/lorwy/Code/github_projects/other/PDF-Writer/FreeType/Debug/libFreeType.a"
  )

# Import target "PDFHummus::LibAesgm" for configuration "Debug"
set_property(TARGET PDFHummus::LibAesgm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(PDFHummus::LibAesgm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibAesgm/Debug/libLibAesgm.a"
  )

# Import target "PDFHummus::LibJpeg" for configuration "Debug"
set_property(TARGET PDFHummus::LibJpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(PDFHummus::LibJpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibJpeg/Debug/libLibJpeg.a"
  )

# Import target "PDFHummus::LibTiff" for configuration "Debug"
set_property(TARGET PDFHummus::LibTiff APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(PDFHummus::LibTiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C;CXX"
  IMPORTED_LOCATION_DEBUG "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibTiff/Debug/libLibTiff.a"
  )

# Import target "PDFHummus::LibPng" for configuration "Debug"
set_property(TARGET PDFHummus::LibPng APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(PDFHummus::LibPng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibPng/Debug/libLibPng.a"
  )

# Import target "PDFHummus::PDFWriter" for configuration "Debug"
set_property(TARGET PDFHummus::PDFWriter APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(PDFHummus::PDFWriter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LOCATION_DEBUG "/Users/lorwy/Code/github_projects/other/PDF-Writer/PDFWriter/Debug/libPDFWriter.a"
  )

# Import target "PDFHummus::Zlib" for configuration "Release"
set_property(TARGET PDFHummus::Zlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PDFHummus::Zlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/lorwy/Code/github_projects/other/PDF-Writer/Zlib/Release/libZlib.a"
  )

# Import target "PDFHummus::FreeType" for configuration "Release"
set_property(TARGET PDFHummus::FreeType APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PDFHummus::FreeType PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/lorwy/Code/github_projects/other/PDF-Writer/FreeType/Release/libFreeType.a"
  )

# Import target "PDFHummus::LibAesgm" for configuration "Release"
set_property(TARGET PDFHummus::LibAesgm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PDFHummus::LibAesgm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibAesgm/Release/libLibAesgm.a"
  )

# Import target "PDFHummus::LibJpeg" for configuration "Release"
set_property(TARGET PDFHummus::LibJpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PDFHummus::LibJpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibJpeg/Release/libLibJpeg.a"
  )

# Import target "PDFHummus::LibTiff" for configuration "Release"
set_property(TARGET PDFHummus::LibTiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PDFHummus::LibTiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LOCATION_RELEASE "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibTiff/Release/libLibTiff.a"
  )

# Import target "PDFHummus::LibPng" for configuration "Release"
set_property(TARGET PDFHummus::LibPng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PDFHummus::LibPng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibPng/Release/libLibPng.a"
  )

# Import target "PDFHummus::PDFWriter" for configuration "Release"
set_property(TARGET PDFHummus::PDFWriter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(PDFHummus::PDFWriter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/Users/lorwy/Code/github_projects/other/PDF-Writer/PDFWriter/Release/libPDFWriter.a"
  )

# Import target "PDFHummus::Zlib" for configuration "MinSizeRel"
set_property(TARGET PDFHummus::Zlib APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(PDFHummus::Zlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/lorwy/Code/github_projects/other/PDF-Writer/Zlib/MinSizeRel/libZlib.a"
  )

# Import target "PDFHummus::FreeType" for configuration "MinSizeRel"
set_property(TARGET PDFHummus::FreeType APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(PDFHummus::FreeType PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/lorwy/Code/github_projects/other/PDF-Writer/FreeType/MinSizeRel/libFreeType.a"
  )

# Import target "PDFHummus::LibAesgm" for configuration "MinSizeRel"
set_property(TARGET PDFHummus::LibAesgm APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(PDFHummus::LibAesgm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibAesgm/MinSizeRel/libLibAesgm.a"
  )

# Import target "PDFHummus::LibJpeg" for configuration "MinSizeRel"
set_property(TARGET PDFHummus::LibJpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(PDFHummus::LibJpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibJpeg/MinSizeRel/libLibJpeg.a"
  )

# Import target "PDFHummus::LibTiff" for configuration "MinSizeRel"
set_property(TARGET PDFHummus::LibTiff APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(PDFHummus::LibTiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C;CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibTiff/MinSizeRel/libLibTiff.a"
  )

# Import target "PDFHummus::LibPng" for configuration "MinSizeRel"
set_property(TARGET PDFHummus::LibPng APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(PDFHummus::LibPng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibPng/MinSizeRel/libLibPng.a"
  )

# Import target "PDFHummus::PDFWriter" for configuration "MinSizeRel"
set_property(TARGET PDFHummus::PDFWriter APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(PDFHummus::PDFWriter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "CXX"
  IMPORTED_LOCATION_MINSIZEREL "/Users/lorwy/Code/github_projects/other/PDF-Writer/PDFWriter/MinSizeRel/libPDFWriter.a"
  )

# Import target "PDFHummus::Zlib" for configuration "RelWithDebInfo"
set_property(TARGET PDFHummus::Zlib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PDFHummus::Zlib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/lorwy/Code/github_projects/other/PDF-Writer/Zlib/RelWithDebInfo/libZlib.a"
  )

# Import target "PDFHummus::FreeType" for configuration "RelWithDebInfo"
set_property(TARGET PDFHummus::FreeType APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PDFHummus::FreeType PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/lorwy/Code/github_projects/other/PDF-Writer/FreeType/RelWithDebInfo/libFreeType.a"
  )

# Import target "PDFHummus::LibAesgm" for configuration "RelWithDebInfo"
set_property(TARGET PDFHummus::LibAesgm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PDFHummus::LibAesgm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibAesgm/RelWithDebInfo/libLibAesgm.a"
  )

# Import target "PDFHummus::LibJpeg" for configuration "RelWithDebInfo"
set_property(TARGET PDFHummus::LibJpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PDFHummus::LibJpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibJpeg/RelWithDebInfo/libLibJpeg.a"
  )

# Import target "PDFHummus::LibTiff" for configuration "RelWithDebInfo"
set_property(TARGET PDFHummus::LibTiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PDFHummus::LibTiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C;CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibTiff/RelWithDebInfo/libLibTiff.a"
  )

# Import target "PDFHummus::LibPng" for configuration "RelWithDebInfo"
set_property(TARGET PDFHummus::LibPng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PDFHummus::LibPng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/lorwy/Code/github_projects/other/PDF-Writer/LibPng/RelWithDebInfo/libLibPng.a"
  )

# Import target "PDFHummus::PDFWriter" for configuration "RelWithDebInfo"
set_property(TARGET PDFHummus::PDFWriter APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(PDFHummus::PDFWriter PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "CXX"
  IMPORTED_LOCATION_RELWITHDEBINFO "/Users/lorwy/Code/github_projects/other/PDF-Writer/PDFWriter/RelWithDebInfo/libPDFWriter.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
